### ISSUE TITLE
Cannot import org.openapitools.client.model.Message;

### ISSUE THREAD

**Issue by trademaxint** [eBay/event-notification-java-sdk#1]
After downloaded the source code, I imported it as a maven project in Intellij:

IntelliJ IDEA 2020.3.2 (Ultimate Edition)
Build #IU-203.7148.57, built on January 25, 2021
Runtime version: 11.0.9.1+11-b1145.77 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
GC: ParNew, ConcurrentMarkSweep
Memory: 1979M
Cores: 12

However, the project cannot figure out how to import ort.openapitools.client.model (e.g. import org.openapitools.client.model.Message; ) so that all entity inside the org.openapitools.client.model cannot be used. Does anyone have the same issue?

**Comment by sekharbans-ebay** [comment]
Hi @trademaxint 

These are code genned.  The generated source files should be under target/generated-sources/openapi.
You should see the compiled classes under target/classes once maven completes.

Thanks
